#!/bin/bash
#
# Setup ValKey as a replica of a constellation master.
# =====================================================
#
# Configures the local /etc/valkey/valkey-gnode.conf to:
#   - Set replicaof <master_ip> <master_port>
#   - Set masterauth <master_password>
#   - Bind replica to localhost AND VPN IP for component reads
#
# Idempotent: safe to re-run. Reverts to standalone if --disable.
#
# Usage:
#   sudo setup-valkey-replica.sh --master <ip> --master-port <port> \
#                                 --master-password-file <path>
#   sudo setup-valkey-replica.sh --disable
#
# After running, restart valkey-gnode to apply:
#   sudo systemctl restart valkey-gnode
#
# Lua functions: ExecStartPost in the systemd unit auto-loads them on every
# restart, so the local replica gets functions even though Redis replication
# does not propagate them.
#

set -euo pipefail

VALKEY_CONF="${VALKEY_CONF:-/etc/valkey/valkey-gnode.conf}"
MASTER_IP=""
MASTER_PORT="47445"
MASTER_PASSWORD_FILE=""
MASTER_USER="gnode_replica"
DISABLE=false

usage() {
    cat <<EOF
Usage:
  $0 --master <ip> --master-port <port> --master-password-file <path>
  $0 --disable

Options:
  --master <ip>                  Master ValKey IP (typically 10.66.0.1 over VPN)
  --master-port <port>           Master ValKey port (default: 47445)
  --master-password-file <path>  Path to file with the master's gnode_replica password
  --master-user <name>           ACL user to replicate as (default: gnode_replica)
  --disable                      Remove replica config, revert to standalone
  -h, --help                     Show this help
EOF
    exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --master)               MASTER_IP="$2"; shift 2 ;;
        --master-port)          MASTER_PORT="$2"; shift 2 ;;
        --master-password-file) MASTER_PASSWORD_FILE="$2"; shift 2 ;;
        --master-user)          MASTER_USER="$2"; shift 2 ;;
        --disable)              DISABLE=true; shift ;;
        -h|--help)              usage 0 ;;
        *)                      echo "Unknown arg: $1" >&2; usage 1 ;;
    esac
done

if [[ ! -f "$VALKEY_CONF" ]]; then
    echo "ERROR: ValKey config not found: $VALKEY_CONF" >&2
    exit 1
fi

if [[ "$EUID" -ne 0 ]]; then
    echo "ERROR: must run as root (writes to $VALKEY_CONF)" >&2
    exit 1
fi

# ── Disable mode: strip replica directives ──────────────────────────────
if [[ "$DISABLE" == "true" ]]; then
    sed -i \
        -e '/^# === GEODINEUM REPLICA CONFIG ===/,/^# === END GEODINEUM REPLICA CONFIG ===/d' \
        "$VALKEY_CONF"
    echo "Replica configuration removed from $VALKEY_CONF"
    echo "Restart with: sudo systemctl restart valkey-gnode"
    exit 0
fi

# ── Validate inputs ─────────────────────────────────────────────────────
if [[ -z "$MASTER_IP" ]]; then
    echo "ERROR: --master <ip> required" >&2
    usage 1
fi

if [[ -z "$MASTER_PASSWORD_FILE" || ! -f "$MASTER_PASSWORD_FILE" ]]; then
    echo "ERROR: --master-password-file <path> required and must exist" >&2
    exit 1
fi

MASTER_PASSWORD=$(cat "$MASTER_PASSWORD_FILE")
if [[ -z "$MASTER_PASSWORD" ]]; then
    echo "ERROR: master password file is empty" >&2
    exit 1
fi

# ── Strip any existing replica config (idempotency) ─────────────────────
sed -i \
    -e '/^# === GEODINEUM REPLICA CONFIG ===/,/^# === END GEODINEUM REPLICA CONFIG ===/d' \
    "$VALKEY_CONF"

# ── Append fresh replica block ──────────────────────────────────────────
cat >> "$VALKEY_CONF" <<EOF

# === GEODINEUM REPLICA CONFIG ===
# Auto-generated by setup-valkey-replica.sh — do not edit manually.
# Remove with: sudo setup-valkey-replica.sh --disable
replicaof ${MASTER_IP} ${MASTER_PORT}
masteruser ${MASTER_USER}
masterauth ${MASTER_PASSWORD}
# === END GEODINEUM REPLICA CONFIG ===
EOF

# Lock down the conf since it now contains a password
chown root:gnode "$VALKEY_CONF"
chmod 640 "$VALKEY_CONF"

echo "Replica configuration written to $VALKEY_CONF"
echo "  master: ${MASTER_IP}:${MASTER_PORT}"
echo "  user:   ${MASTER_USER}"
echo "  password: read from $MASTER_PASSWORD_FILE"
echo ""
echo "Apply with: sudo systemctl restart valkey-gnode"
echo "Verify with: REDISCLI_AUTH=... valkey-cli -p ${MASTER_PORT} INFO replication"
