// Command Handler Module
//
// Decomposed from the monolithic command_handler.rs into SRP-compliant modules.
// Each handler category lives in its own file with a register() function
// that populates the command registry.
//
// Module structure:
//   types.rs       - Shared types, constants, utilities
//   system.rs      - ping, health, version, echo, status, load_update, node_info, site_info
//   stream.rs      - stream_info, stream_group_info, stream_consumer_info, stream_pending
//   config.rs      - config_get, config_set, config_list
//   diagnostic.rs  - debug_info, memory_stats, thread_status, connection_status, etc.
//   geometric.rs   - geometric_discover, geometric_discover_range, geometric_store_topology, etc.
//   service.rs     - registerService, deregisterService, discover_with_endpoints
//   introspection.rs - service_describe (entity introspection with tier/health)
//   topology_custom.rs    - custom_topology_discover, distance, knn, similarity
//   topology_unified.rs   - topo_create, topo_register, topo_add_edge, etc.
//
// CMS extension (requires --features cms; handler sources live in the
// companion repo gNode-CMS, discovered via GNODE_EXT_CMS_PATH or sibling
// clone):
//   content.rs     - content_store, content_retrieve, template_fragment, asset_bundle  [cms]
//   format.rs      - register_format, list_formats, detect_format, convert_format      [cms]
//   template.rs    - render_template, serve_fragment, list_templates, discover_*        [cms]
//   asset.rs       - asset_store, asset_get, asset_delete, asset_list, manifest_*       [cms]
//
// Signed extensions (optional): discovered at build time from GNODE_EXT_DIR.
// Each signed extension declares its feature gate and handler files in a
// manifest; see build.rs for the discovery + verification flow.

// --- Base modules (always compiled) ---
pub mod types;
pub mod system;
pub mod stream;
pub mod config;
pub mod diagnostic;
pub mod geometric;
pub mod service;
pub mod introspection;
pub mod topology_custom;
pub mod topology_unified;
pub mod direct_channel;
pub mod relay_ops;

// CMS handlers (content/format/template/asset) come exclusively
// via the signed-extension pipeline now. They were previously inlined
// here via include!("$OUT_DIR/cms_handlers/<file>") which only existed
// when the (now-removed) `cms` Cargo feature was active. With this
// unification, build.rs stages CMS handlers (and any other signed
// extension's handlers) into OUT_DIR/<ext_name>_handlers/ and the
// `include!(ext_handlers.rs)` line below dispatches the generated
// `register_signed_extensions()` function from build.rs.

// --- Signed extensions (generated by build.rs from GNODE_EXT_DIR) ---
// Expands to `pub mod ext_<name> { pub mod <handler> { ... } }` blocks for
// each verified extension. Empty when no signed extensions are configured.
include!(concat!(env!("OUT_DIR"), "/ext_handlers.rs"));

// Re-export core types used by the rest of the codebase
pub use types::{
    // Constants (service tier defaults)
    DISCOVERY_DIMENSIONS,
    TOTAL_DIMENSIONS,
    SERVICE_DIMENSIONS,

    // Schema-driven generic functions (multi-tier; pass dim count + dim map)
    build_capability_vector,
    discovery_point,

    // Service tier convenience wrappers
    get_service_dimensions,
    build_service_capability_vector,
    discovery_point_from_full,

    // Core types
    CommandResult,
    CommandDescriptor,
    CommandHandlerFn,
    AsyncCommandHandlerFn,

    // Utilities
    parse_parameters,
    default_group,
    get_memory_usage_kb,
    calculate_euclidean_distance,
    fixed_vector_to_capabilities,
};
